# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
    
- task: Maven@3
  inputs:
    mavenPomFile: '$(System.DefaultWorkingDirectory)/LA_Sikuli/pom.xml'
    mavenOptions: '-Xmx3072m'
   # javaHomeOption: 'JDKVersion'
   # jdkVersionOption: '1.8'
   # jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    #testResultsFiles: '**/surefire-reports/TEST-*.xml'
    #testResultsFiles:  '**/junitreports/TEST-*.xml'
    testResultsFiles:  '**/LA*.html'
    goals: 'package'

# Publish Test Results
# Publish test results to Azure Pipelines
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit, cTest
    testResultsFiles: '**/LA*.html' 
    #searchFolder: '$(System.DefaultWorkingDirectory)' # Optional
    #mergeTestResults: false # Optional
    #failTaskOnFailedTests: false # Optional
    #testRunTitle: # Optional
    #buildPlatform: # Optional
    #buildConfiguration: # Optional
    publishRunAttachments: true # Optional

#- task: CopyFiles@2
#  inputs:
#    contents: '**'
#    targetFolder: '$(Build.ArtifactStagingDirectory)'
    
#- task: PublishBuildArtifacts@1
#  inputs:
 #   pathToPublish: '$(Build.ArtifactStagingDirectory)'
  #  artifactName: 'MyBuildOutputs'